functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - В каталоге должна быть реализована постраничная навигация 
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре
  - На странице товара и в каталоге должны выводиться: название, рейтинг, цена со скидкой и без  
  - Пользователь должен иметь возможность добавлять товары в корзину и продолжить выбор товаров в каталоге
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - В корзине пользователь должен иметь возможность удалить товар и оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию на русский и английский языки
  - Приложение должно быть без перезагрузки страниц
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен иметь адаптивную верстку и быть удобным на мобильных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть доступен для пользователей без использования VPN 
  - Корзина должна храниться в сессии браузера
implicit:
  - Сайт должен загружаться за приемлемое время 
  - Пользователь не должен видеть товар, который уже нельзя купить
  - При фильтрации товаров по цене должна учитываться скидка
  - Не должна ломаться верстка при переводе на другие языки
