name: Alena Derkacheva
job: QA Engineer
level: junior
email: al.derkacheva@yandex.ru
description: |люблю горы, читать и узнавать новое
skills: # Список навыков в виде списка, можете написать сюда что-то свое
  - Функциональное тестирование
  - Написание багрепортов
  - SQL
  - Английский язык В1
