- summary: |
      Описания товаров не переведены на русский язык
    status: fail

  bugreports:
- summary: |
 Описания товаров не переведены на русский язык
  environment: |
   Веб-браузер Mozilla Firefox версия 148.0 (64-разрядная)
   ОС Windows 10 Pro
  steps-to-reproduce: |
    1.Заходим на главную страницу по ссылке https://products-store.hexlet.app/
    2.В правом верхнем углу нажать на Language
    3. Выбрать Rassian
  expected-result: |
     Все элементы интерфейса и описания товаров переведены на русский язык
  actual-result: |
   Перевелись только элементы интерфейса

   - summary: |
     Раскладка кириллица, не происходит поиск товара по ключевому слову или категории
     status: fail

  bugreports:
- summary: |   
  environment: |
   Веб-браузер Mozilla Firefox версия 148.0 (64-разрядная)
   ОС Windows 10 Pro
  steps-to-reproduce: |
    1.Заходим на главную страницу по ссылке https://products-store.hexlet.app/
    2.В правом верхнем углу нажать на Language
    3.Выбрать Rassian
    4.Начать вводить в поле поиска часть слова "са", раскладка кириллица
  expected-result: |
     Появляются товары отвечающие заданым кретериям
  actual-result: |
   Ответ интернет-магазина "Ничего не найдено!"

    
