summary: |
    Поиск товара по ключевому слову
requirement:|
    При верном вводе ключевого слова должен отображаться список товаров
  prerequisites: |
    Это условия, которые необходимы для проведения тест кейса. Они должны быть выполнены еще до запуска тест кейса.
    Открыта главная страница сайта
  test-data: |
    Тестовые данные
    Слово поиска = "cat"
  steps:
    - Начать вводить в поле поиска часть слова "са"
    - Дождаться появления списка товаров
    - Выбрать из списка "Cat food"
  expected-result: |
    Остался только нужный товар

    - summary: |
    Пользователь должен иметь возможность фильтровать товары 
  requirement: |
    При вводе диапозона цены должен отображаться список подходящих товаров
  prerequisites:
    Открыта главная страница сайта
  test-data: |
    Диапозон цены = от 119 до 3999
  steps:
    - В поле параллельно «From» ввести 119
    - В поле параллельно «To» ввести 3999
  expected-result: |
    Отображаться список подходящих товаров

    - summary: |
    Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  requirement: |
    При нажатии на карточку товара клиент должен получить подробную информацию о товаре
  prerequisites:
    Открыта главная страница сайта
  test-data: |
    Товар = Annibale Colombo Bed
  steps:
    - Выбираем товар из списка
    - Наводим мышку на карточку товара 
    - Нажимаем левую кнопку мыши один раз
  expected-result: |
    Открывается полная информация о товаре

    - summary: |
    Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  requirement: |
    Добавленные товары в корзину можно просмотреть
  prerequisites:
    Открыта главная страница сайта
  test-data: |
    В корзину добавлено 2 товара = Powder Canister и Dior J'adore
  steps:
    - Нажимаем Add to cart для Powder Canister
    - Нажимаем Add to cart для Dior J'adore
    - Нажимаем кнопку Сart
  expected-result: |
    В корзину добавлено 2 просматваемых товара

    - summary: |
    Пользователь должен иметь возможность переключить язык интерфейса
  requirement: |
    При выборе испанского языка происходит смена с английского
  prerequisites:
    Пользователь находится на главной странице
  test-data: |
    Language = Spanish
  steps:
    - Правый верхний угол вкладка Language
    - Нажимаем на вкладку Language 
    - В открывшейся вкладке нажимаем на Spanish
  expected-result: |
    Основные атрибуты страницы переведены на испанский язык

    - summary: |
    - Сайт должен иметь локализацию (перевод) на русский и английский языки
  requirement: |
    Все элементы интерфейса и описания товаров переведены на русский язык
  prerequisites:
    Пользователь находится на главной странице
  test-data: |
    Language = Russian
  steps:
    - Правый верхний угол вкладка Language
    - Нажимаем на вкладку Language 
    - В открывшейся вкладке нажимаем на Russian
  expected-result: |
    Элементы интерфейса и описания товаров переведены на русский язык
